# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Default Value', max_length=200),
        ),
    ]
